// https://github.com/vercel/next-learn/blob/main/dashboard/final-example/app/lib/placeholder-data.js

const users = [
  {
    id: 1,
    name: "admin",
    email: "admin@example.com",
    pwd: "admin123",
    home_address: null,
    role: "admin",
    status: "validated",
  },
  {
    id: 2,
    name: "Ana",
    email: "ana@example.com",
    pwd: "ana",
    home_address: "Plaza Central, Ciudad",
    role: "manager",
    status: "validated",
  },
  {
    id: 3,
    name: "Bea",
    email: "bea@example.com",
    pwd: "bea",
    home_address: "Avenida Principal, Ciudad",
    role: "manager",
    status: "validated",
  },
  {
    id: 4,
    name: "Carlos",
    email: "carlos@example.com",
    pwd: "carlos123",
    home_address: "Calle Mayor, 45",
    role: "manager",
    status: "validated",
  },
  {
    id: 5,
    name: "Diana",
    email: "diana@store.com",
    pwd: "diana456",
    home_address: "Calle Libertad, 10",
    role: "manager",
    status: "validated",
  },
  {
    id: 6,
    name: "Elena",
    email: "elena@company.com",
    pwd: "elena789",
    home_address: "Avenida del Sol, 21",
    role: "manager",
    status: "pending",
  },
  {
    id: 7,
    name: "Francisco",
    email: "francisco@email.com",
    pwd: "francisco00",
    home_address: "Calle Luna, 32",
    role: "manager",
    status: "pending",
  },
  {
    id: 8,
    name: "Gloria",
    email: "gloria@store.com",
    pwd: "gloria111",
    home_address: "Calle Estacion, 1",
    role: "manager",
    status: "pending",
  },
  {
    id: 9,
    name: "Hugo",
    email: "hugo@company.com",
    pwd: "hugo222",
    home_address: null,
    role: "manager",
    status: "pending",
  },
  {
    id: 10,
    name: "Irene",
    email: "irene@email.com",
    pwd: "irene333",
    home_address: "Calle Principal, 7",
    role: "manager",
    status: "pending",
  },
  {
    id: 11,
    name: "Javier",
    email: "javier@store.com",
    pwd: "javier444",
    home_address: "Calle Norte, 56",
    role: "manager",
    status: "pending",
  },
  {
    id: 12,
    name: "Karina",
    email: "karina@company.com",
    pwd: "karina555",
    home_address: "Calle Sur, 89",
    role: "manager",
    status: "pending",
  },
  {
    id: 13,
    name: "Luis",
    email: "luis@email.com",
    pwd: "luis666",
    home_address: "Calle Oriente, 23",
    role: "manager",
    status: "pending",
  },
  {
    id: 14,
    name: "Pepe",
    email: "pepe@example.com",
    pwd: "pepe",
    home_address: "Calle 123, Ciudad",
    role: "customer",
    status: "validated",
  },
];

const stores = [
  {
    name: "Store 1",
    address: "123 Main St",
    city: "City 1",
    state: "State 1",
    postcode: "12345",
    phone_number: "123-456-7890",
    manager_id: 2,
  },
  {
    name: "Store 2",
    address: "456 Elm St",
    city: "City 2",
    state: "State 2",
    postcode: "23456",
    phone_number: "234-567-8901",
    manager_id: 3,
  },
  {
    name: "Store 3",
    address: "789 Oak St",
    city: "City 3",
    state: "State 3",
    postcode: "34567",
    phone_number: "345-678-9012",
    manager_id: 4,
  },
  {
    name: "Store 4",
    address: "1011 Pine St",
    city: "City 4",
    state: "State 4",
    postcode: "45678",
    phone_number: "456-789-0123",
    manager_id: 5,
  },
  {
    name: "Store 5",
    address: "1213 Cedar St",
    city: "City 5",
    state: "State 5",
    postcode: "56789",
    phone_number: "567-890-1234",
    manager_id: 6,
  },
  {
    name: "Store 6",
    address: "1415 Maple St",
    city: "City 6",
    state: "State 6",
    postcode: "67890",
    phone_number: "678-901-2345",
    manager_id: 7,
  },
  {
    name: "Store 7",
    address: "1617 Birch St",
    city: "City 7",
    state: "State 7",
    postcode: "78901",
    phone_number: "789-012-3456",
    manager_id: 8,
  },
  {
    name: "Store 8",
    address: "1819 Walnut St",
    city: "City 8",
    state: "State 8",
    postcode: "89012",
    phone_number: "890-123-4567",
    manager_id: 9,
  },
  {
    name: "Store 9",
    address: "2021 Ash St",
    city: "City 9",
    state: "State 9",
    postcode: "90123",
    phone_number: "901-234-5678",
    manager_id: 10,
  },
  {
    name: "Store 10",
    address: "2223 Spruce St",
    city: "City 10",
    state: "State 10",
    postcode: "01234",
    phone_number: "012-345-6789",
    manager_id: 11,
  },
  {
    name: "Store 11",
    address: "2425 Fir St",
    city: "City 11",
    state: "State 11",
    postcode: "12345",
    phone_number: "123-456-7890",
    manager_id: 12,
  },
  {
    name: "Store 12",
    address: "2627 Cedar St",
    city: "City 12",
    state: "State 12",
    postcode: "23456",
    phone_number: "234-567-8901",
    manager_id: 13,
  },
];

const pizzas = [
  {
    name: "Margarita",
    description: "Tomate, mozzarella y albahaca",
    price: 8.99,
    photo: "margarita.webp",
  },
  {
    name: "Pepperoni",
    description: "Tomate, mozzarella y pepperoni",
    price: 9.99,
    photo: "pepperoni.webp",
  },
  {
    name: "Hawaiana",
    description: "Tomate, mozzarella, piña y jamón",
    price: 10.99,
    photo: "hawaiana.jpg",
  },
  {
    name: "Barbacoa",
    description: "Tomate, mozzarella, carne de res, cebolla y salsa barbacoa",
    price: 11.99,
    photo: "barbacoa.jpg",
  },
  {
    name: "Vegetariana",
    description: "Tomate, mozzarella, champiñones, pimientos y aceitunas",
    price: 10.49,
    photo: "vegetariana.webp",
  },
  {
    name: "Cuatro quesos",
    description:
      "Tomate, mozzarella, queso azul, queso de cabra y queso parmesano",
    price: 12.99,
    photo: "cuatroquesos.avif",
  },
  {
    name: "Napolitana",
    description: "Tomate, mozzarella, anchoas, aceitunas y alcaparras",
    price: 11.49,
    photo: "napolitana.jpg",
  },
  {
    name: "Calzone",
    description:
      "Masa de pizza rellena de tomate, mozzarella, pepperoni y champiñones",
    price: 12.49,
    photo: "calzone.webp",
  },
  {
    name: "Prosciutto e rúcula",
    description: "Tomate, mozzarella, jamón crudo y rúcula",
    price: 11.99,
    photo: "prosciuttoerucula.jpg",
  },
  {
    name: "Carbonara",
    description: "Tomate, mozzarella, panceta, huevo y parmesano",
    price: 12.99,
    photo: "carbonara.avif",
  },
  {
    name: "Mexicana",
    description: "Tomate, mozzarella, carne de res, jalapeños y guacamole",
    price: 11.99,
    photo: "mexicana.jpg",
  },
  {
    name: "Bufalina",
    description: "Tomate, mozzarella de búfala y albahaca fresca",
    price: 13.49,
    photo: "bufalina.jpg",
  },
];

const orders = [];

const order_lines = [];

module.exports = {
  users,
  stores,
  pizzas,
  orders,
  order_lines,
};
